**ANN is standas for the artifical neural network**
- steps of working with ANN
- Dataset import and apply the model preprocessing - mising value handle categorical to numerical data in convert's

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Attrition - Attrition.csv')

In [ ]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
# import the deep learning libracy
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
df=df.dropna()

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
# df.isnull().sum()

In [ ]:
x=df.drop(columns=['Attrition'],axis=1)
y=df['Attrition']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
# convert categorical to numerical
categorical_features = ['BusinessTravel',
                       'Department',
                       'EducationField',
                       'Gender',
                       'JobRole',
                       'MaritalStatus',
                       'Over18',
                       'OverTime']

In [ ]:
x_encoded =pd.get_dummies(x,columns=categorical_features,drop_first=True)

In [ ]:
x_encoded=x_encoded.astype(int)

In [ ]:
# x_encoded

In [ ]:
lb=LabelEncoder()

In [ ]:
y_encoded=lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_encoded,y_encoded,test_size=0.2,random_state=42)

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [ ]:
# Architecture of ANN
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',input_dim=x_train_scaled.shape[1]),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=42,activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1,activation='sigmoid')

])

In [ ]:
# now compiles the models
loss_fu=tf.keras.losses.BinaryCrossentropy()
metrics=['accuracy']

learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate,momentum=momentum,nesterov=True)

In [ ]:
model.compile(optimizer=optimizer,loss=loss_fu,metrics=metrics)

In [ ]:
# train model
model.fit(x_train_scaled,y_train,epochs=50,batch_size=8,validation_split=0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.7249 - loss: 0.5710 - val_accuracy: 0.7966 - val_loss: 0.4962
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8299 - loss: 0.4755 - val_accuracy: 0.7966 - val_loss: 0.4753
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8328 - loss: 0.4282 - val_accuracy: 0.7966 - val_loss: 0.4596
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8434 - loss: 0.4039 - val_accuracy: 0.7966 - val_loss: 0.4460
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8334 - loss: 0.4068 - val_accuracy: 0.7966 - val_loss: 0.4347
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8486 - loss: 0.3688 - val_accuracy: 0.8051 - val_loss: 0.4246
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8669 - loss: 0.3697 - val_accuracy: 0.8220 - val_loss: 0.4165
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8338 - loss: 0.3725 - val_accuracy: 0.8220 - val_loss: 0.4105
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8600 - loss: 0.3639 - val_accuracy: 0.8220 - val_loss: 0.4072
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8650 - loss: 0.3427 - val_accuracy: 0.8475 - val_loss: 0.4010
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8734 - loss: 0.3318 - val_accuracy: 0.8559 - val_loss: 0.3959
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8733 - loss: 0.3374 - val_accuracy: 0.8475 - val_loss: 0.3920
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8931 - loss: 0.2955 - val_accuracy: 0.8220 - val_loss: 0.3888
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8738 - loss: 0.3000 - val_accuracy: 0.8305 - val_loss: 0.3877
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8850 - loss: 0.3097 - val_accuracy: 0.8305 - val_loss: 0.3881
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8730 - loss: 0.3232 - val_accuracy: 0.8220 - val_loss: 0.3896
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8422 - loss: 0.3460 - val_accuracy: 0.8305 - val_loss: 0.3914
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8697 - loss: 0.3108 - val_accuracy: 0.8220 - val_loss: 0.3885
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2786 - val_accuracy: 0.8305 - val_loss: 0.3862
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8807 - loss: 0.2740 - val_accuracy: 0.8305 - val_loss: 0.3892
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8824 - loss: 0.2887 - val_accuracy: 0.8220 - val_loss: 0.3893
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8911 - loss: 0.2798 - val_accuracy: 0.8220 - val_loss: 0.3899
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8784 - loss: 0.3020 - val_accuracy: 0.8220 - val_loss: 0.3906
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9010 - loss: 0.2542 - val_accuracy: 0.8305 - val_loss: 0.3916
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8811 - loss: 0.2871 - val_accuracy: 0.8136 - val_loss: 0.3908
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8986 - loss: 0.2579 - val_accuracy: 0.8305 - val_loss: 0.3925
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8887 - loss: 0.2727 - val_accuracy: 0.8136 - val_loss: 0.3949
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9118 - loss: 0.2445 - val_accuracy: 0.8220 - val_loss: 0.3896
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9140 - loss: 0.2287 - val_accuracy: 0.8136 - val_loss: 0.3928
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9172 - loss: 0.2372 - val_accuracy: 0.8136 - val_loss: 0.3967
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9083 - loss: 0.2200 - val_accuracy: 0.8136 - val_loss: 0.4032
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9059 - loss: 0.2378 - val_accuracy: 0.8136 - val_loss: 0.4054
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9192 - loss: 0.2231 - val_accuracy: 0.8136 - val_loss: 0.4090
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8946 - loss: 0.2402 - val_accuracy: 0.7966 - val_loss: 0.4077
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9154 - loss: 0.2164 - val_accuracy: 0.7966 - val_loss: 0.4049
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9151 - loss: 0.2110 - val_accuracy: 0.7966 - val_loss: 0.4041
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9162 - loss: 0.2054 - val_accuracy: 0.7881 - val_loss: 0.4066
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2352 - val_accuracy: 0.7966 - val_loss: 0.4160
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9033 - loss: 0.2300 - val_accuracy: 0.7966 - val_loss: 0.4194
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9120 - loss: 0.2240 - val_accuracy: 0.7966 - val_loss: 0.4159
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9232 - loss: 0.2112 - val_accuracy: 0.8051 - val_loss: 0.4196
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9212 - loss: 0.2127 - val_accuracy: 0.7966 - val_loss: 0.4254
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9128 - loss: 0.1993 - val_accuracy: 0.8051 - val_loss: 0.4189
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9006 - loss: 0.2430 - val_accuracy: 0.7966 - val_loss: 0.4180
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9093 - loss: 0.2166 - val_accuracy: 0.7881 - val_loss: 0.4218
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9331 - loss: 0.2169 - val_accuracy: 0.8051 - val_loss: 0.4223
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9072 - loss: 0.2144 - val_accuracy: 0.7966 - val_loss: 0.4229
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9233 - loss: 0.2117 - val_accuracy: 0.7966 - val_loss: 0.4261
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9067 - loss: 0.1929 - val_accuracy: 0.7966 - val_loss: 0.4232
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9249 - loss: 0.1920 - val_accuracy: 0.7966 - val_loss: 0.4270

In [ ]:
# calculated accuracy ,loss
loss,accuracy=model.evaluate(x_test_scaled,y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8859 - loss: 0.3681